export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_USER_GROUPS = "GET_USER_GROUPS";
export const GET_CURRENT_GROUP = "GET_CURRENT_GROUP";
export const GET_PENDING_INVITES = "GET_PENDING_INVITES";